### ISSUE TITLE
import-config failing with git & s3 protocols

### ISSUE THREAD

**Issue by rbayliss** [chanzuckerberg/blessclient#109]
Hey there, 
There's certainly a chance this is user error, but I'm running blessclient 0.4.1, and the following imports are failing for me:

```
> blessclient import-config -k ~/.ssh/id_rsa github.com/myorg/myrepo//docs/blessclient.yml?ref=bless
fatal: repository 'https://github.com/myorg/' not found 

> blessclient import-config s3://my-bucket/BLESS/blessclient.yml
Could not fetch s3://my-bucket/BLESS/blessclient.yml: NoSuchBucket: The specified bucket does not exist
```

Interestingly, I accidentally ran this and it succeeded:
```
blessclient import-config http://github.com//examples/config.yml -k ~/.ssh/id_rsa
```

Not sure what to make of this. Am I doing it wrong?

**Comment by edulop91** [comment]
For git: if you have a private git repo then usually you can use ssh instead of https. `git@github.com:/org/repo/config.yml`

**Comment by edulop91** [comment]
for s3 the following should work 
```
AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=${profile} blessclient import-config s3://${bucket}/config.yml
```

**Comment by edulop91** [comment]
Opened an associated ticket for the last piece

**Comment by rbayliss** [comment]
Ah, thank you.  I was trying to use the same syntax we use for Terraform modules, but it seems like only a subset is supported.  I was able to get a successful config import, but only when the config file lives at the root of the repository.  If it's in a directory (say `docs`), I get the following error:
```
myorg/myrepo/docs is not a valid repository name
```
Not a critical issue for us right now because we can just move it to the root of the repository, but it would definitely be nice to keep it in a directory.

**Comment by edulop91** [comment]
interesting, i'll open another bug on that
