### ISSUE TITLE
MFA not supported for non-okta

### ISSUE THREAD

**Issue by spencerprovost** [chanzuckerberg/blessclient#129]
We use 99design's aws-vault for mfa. It would be great if there were a place in the configuration for a custom command to execute in order to assume the role instead of the client assuming the role. Since ssh exec can't take stdin, we could just create a bash_profile function to set everything up for the ssh connection and then ssh into the desired host?
```
function mysshcommand {
	blessclient run
	ssh $1
}
```
Essentially taking the `blessclient run` out of the ssh config and putting it into a bash profile function, therefore able to take stdin.

**Comment by edulop91** [comment]
@spencerprovost wondering if something like https://github.com/chanzuckerberg/blessclient/issues/107 is helpful?

**Comment by edulop91** [comment]
Nvm, I see the situation you're describing is a bit different. Could you provide a bit more context around how things are configured in your end and what error you get if you try doing something like 
```
function mysshcommand {
	aws-vault exec foo -- blessclient run
	ssh $1
}
```

**Comment by spencerprovost** [comment]
We would like to enforce the user to only encrypt the kmsauth key with their username in the from field (so we can easily see in the auth log who logged in). We would also like to enforce mfa when executing the lambda (we do this by enforcing mfa in order to assume the role). The issue I am running into is that if we do that was described in #107, it allows us to enforce mfa but the role is then executing everything, including the kmsauth request and we are not able to enforce the condition that you can only encrypt with your username, since the username under that context is the role name.  

Essentially we need to execute the blessclient as normal under the user context, but then run our own command to assume the role which requires mfa.

**Comment by edulop91** [comment]
Just out of curiosity, if you do something like `blessclient run || true && aws-vault exec foo -- blessclient run` so that the first runs in the user context and generates a kmsauth token (but fails to assume the role) and the second call uses the cached kms token and then assumes the lambda role

**Comment by spencerprovost** [comment]
That would actually work! Just running into an issue where the second time it is run it tries to redo the kmsauth part and errors out. Is there any way to tell it to re-use the kmsauth token if valid?

**Comment by edulop91** [comment]
I'm looking for a quick hack so that you're not blocked (definitely not a solution). It might be doing more thorough checks on the validity of the kmsauth token than I remembered. 

Another option I was thinking is that aws-vault can land you into a user context instead of a role (is this correct? i've never used aws-vault myself). And then we can teach blessclient how to deal with MFA for the assume role bit

**Comment by spencerprovost** [comment]
I'll try and see if aws-vault will just do mfa for the user context, then I think it would all work.

**Comment by spencerprovost** [comment]
Was able to configure aws-vault to validate mfa for just the user, without assuming the role. It then runs the kmsauth encrypt portion as the user and since the user already provided mfa it allows the user to assume to the role that executes the lambda! Thank you so much for the help, bless and this blessclient is amazing!
