### ISSUE TITLE
 Error invoking lambda function BLESS: AccessDenied: User: arn:aws:sts::536123028970:assumed-role/bastion-ap-south-1/i-0d23a30ff875c60d5 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::536123028970:role/bastion-ap-south-1

### ISSUE THREAD

**Issue by kshitijsharma21** [chanzuckerberg/blessclient#138]
Error invoking lambda function BLESS: AccessDenied: User: arn:aws:sts::536123028970:assumed-role/bastion-ap-south-1/i-0d23a30ff875c60d5 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::536123028970:role/bastion-ap-south-1
status code: 403, request id: 7e1fc8a1-fafe-11e9-8f64-c7bfb6ecd78e

I am trying to invoke lambda from an instanve which has the appropriate roles.

**Comment by edulop91** [comment]
Hi @kshitijsharma21, are you able to assume the role from your instance without blessclient? Directly using the aws cli or something similar?

**Comment by kshitijsharma21** [comment]
@EdmundKorley Issue Resolved. Thanks ! :)
