### ISSUE TITLE
AWS IAM policy when using okta?

### ISSUE THREAD

**Issue by marranz** [chanzuckerberg/blessclient#147]
Hi,

I'm using blessclient + okta. Everything looks good except the iam policy that allows my users to generate the kms token.

The cause is that the content of the 'from' encryption context on blessclient is name.surename@domain.co.uk, but the variable aws:username looks like evaluating something different. have anyone found this issue?

This is the whole policy i'm using:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "kms:Encrypt",
            "Resource": "arn:aws:kms:eu-west-1:xxxxx:key/xxxxxx",
            "Condition": {
                "StringEquals": {
                    "kms:EncryptionContext:to": [
                        "bless"
                    ],
                    "kms:EncryptionContext:user_type": "user",
                    "kms:EncryptionContext:from": "${aws:username}"
                }
            }
        }
    ]
}
```

I get a **KMS encryption failed** error when i run the client. 

When i remove this line
`"kms:EncryptionContext:from": "${aws:username}"`

Everything works and i get my certificate generated and working.

Any help would be appreciated.

Thanks!

**Comment by edulop91** [comment]
Yep! You can use [SAML attributes](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html) to do the conditional. Something like the following could work:
```
Condition:
                StringEquals:
                  'kms:EncryptionContext:user_type': 'user'
                  'kms:EncryptionContext:from': '${SAML:sub}'
```

**Comment by edulop91** [comment]
Going to close this. We can re open if doesn’t work!
