### ISSUE TITLE
Duplicate certificate entry in ssh-agent

### ISSUE THREAD

**Issue by mbonnafon** [chanzuckerberg/blessclient#148]
Hi,

Thank you for fixing the last issue for the timeSkew!

I have noticed that when a user has a valid certificate in his ssh-agent and deletes this certificate on his machine, the next run of blessclient will generate a new certificate and add this new certificate to the ssh-agent. This will cause a duplicate of the certificate in the ssh-agent.

The steps I have taken to reproduce the error:
1 - I cleaned my ssh-agent (ssh-add -D) & removed the certificate
2 - Ran blessclient
3 - Removed the certificate
4 - Ran blessclient
5 - Checked entries in my ssh-agent (ssh-add -L)

Maybe before updating the ssh-agent
here https://github.com/chanzuckerberg/blessclient/blob/3be319cedeef204810a5e8ae51d844d3cc8aabc8/pkg/bless/client.go#L129 or here https://github.com/chanzuckerberg/blessclient/blob/3be319cedeef204810a5e8ae51d844d3cc8aabc8/pkg/bless/client.go#L170 we can remove the previous certificate with https://github.com/chanzuckerberg/blessclient/blob/3be319cedeef204810a5e8ae51d844d3cc8aabc8/vendor/golang.org/x/crypto/ssh/agent/client.go#L57

Do you think this could be reasonable?

Thank you!
Marc

**Comment by edulop91** [comment]
@mbonnafon Sounds reasonable! Just curious, what error are you seeing due to the duplicate certs in the agent?

**Comment by mbonnafon** [comment]
@edulop91 Currently I don't see any errors due to duplicate certificates in the agent, that's more for a cleanliness purpose in order to avoid multiple certificates for the same key pair in the agent.
