### ISSUE TITLE
blessclient is incompatible with EC keys

### ISSUE THREAD

**Issue by mbarrien** [chanzuckerberg/blessclient#43]
Multiple issues with elliptic curve keys (i.e. ed25519):
1) Unable to run blessclient import-config, since it seems hard coded to look for my key in ~/.ssh/id_rsa instead of ~/.ssh/id_ed25519. Could not find config flags to override that.
2) After manually setting up my blessclient config.yml (to work around issues with EC keys on import), I get the following error:
```
$ blessclient run
WARN[0007] Error adding certificate to ssh-agent, is your ssh-agent running?  error="Could not parse private key: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2"
```
Per suggestion, setting `update_ssh_agent: false` looks like a workaround

**Comment by edulop91** [comment]
resolved https://github.com/chanzuckerberg/blessclient/pull/44!
