### ISSUE TITLE
Manage Bless SSH certificates and keys in ssh-agent

### ISSUE THREAD

**Issue by StevenACoffman** [chanzuckerberg/blessclient#67]
When you change wifi, or the bless certificates expire, you need to add or remove SSH private keys into the SSH authentication agent for implementing single sign-on with SSH. I made a dumb utility to manage that in golang over here: [Manage ssh-agent for Bless Certificates in Golang](https://gist.github.com/StevenACoffman/8e2096e7583f3a67fe3d6280b2cb882c)

Are you interested in me cleaning that up and contributing it?

**Comment by StevenACoffman** [comment]
Oh, you have something similar already. Nevermind. Thanks!

**Comment by edulop91** [comment]
:smile: thanks for the offer!
