### ISSUE TITLE
SSH key read error

### ISSUE THREAD

**Issue by vivianho** [chanzuckerberg/blessclient#88]
I'm running on master (SHA `d1991cbcd54a6f54055ed0e2b6335518c04aa4e8`) and getting this error:

```
➜  blessclient git:(master) ✗ go run main.go
# github.com/chanzuckerberg/blessclient/pkg/ssh
pkg/ssh/ssh.go:190:112: k.Size undefined (type *rsa.PrivateKey has no field or method Size)
```

I'm using an RSA key for SSH.

**Comment by vivianho** [comment]
@edulop91 is this something you can help with?

**Comment by edulop91** [comment]
yep, give it a try. i'll add a note to the readme about this

**Comment by vivianho** [comment]
Fixed, thanks! 👍
